sudo: required
language: java
jdk:
- oraclejdk8
services:
- docker
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
script:
- wget https://github.com/openshift/origin/releases/download/v1.3.0-alpha.3/openshift-origin-client-tools-v1.3.0-alpha.3-7998ae4-linux-64bit.tar.gz -O oclient.tar.gz
- tar xzvf oclient.tar.gz
- export PATH=openshift-origin-client-tools-v1.3.0-alpha.3-7998ae4-linux-64bit:$PATH
- oc cluster up
- sleep 20
- cat /etc/hosts
- ./scripts/run_tests.sh
after_failure:
- ./scripts/print_logs.sh
env:
  global:
  - secure: iZYkPrDvU/EXON5/7M5q7n7ZkZ9lm1Nh3zscT2h1t91BQ34t4Vdf9GTCyGSlCaBozo5xsx3lsheA4NjjBEEImPAPXS5kvSXlwpzyqQdkStR0yXlynMU/baygWLx+l+ZYa4b0CGZgEiuULdV+PnVGFxE0fIEnU0NVlrhZEuninWTiCX/X4uPrAY8J64SYzymbqL+pQqKlpXAEURMMNYYnTWhd2rrYn2XJthxYtoRuddCfh2O1HlGZf8Wsgno9E9bsEGD0a8MTtBJ5/TP8T1h7RZ7c0DdmJkUauP8ooX410swiox6jXFTa14aFK4KuRziNuf+KkN1NZC5gns2+eRbQ4EO9Tyg7eyH9RADMiEeo6cxVVw8ipcj4HMA7U5aXVNoZfDZN+4CxwZ7oazWkXV1gcmQQaq0gkjpwv0iV+9fT+/hb+KWezm0EktAr4XuoV55LZVhuphjOxBbXRAnTq/JzbRfS+GHypG9bYIGN9MSWVj3dUk7tzYpLlo/lCp7Y9zBdV80P/pCpb0FREkbQRu3kZXi0hGE+V3BoOfP5BOMuXbjapSNhowS1j6T4UKLAimyMKKDEtjlFwz/KQyDdYvXjieJoze3+7XJ5toj2RpcY+LIFRsBxTaWiCLHIZisMOEWT+ZbW3tAlbf+rgBWdUXBoGJawHPXNg5+NFpGGqWbZO48=
  - secure: sWh+bO5wtXB8vKeCyA7JKS+NHokz7DvnNn4z55VwRGp2JPQl1JahRKIkf4J27nN/UmW3kaJqEGrmAtk4fQWN8l6ZbFaykCuAwVYwl8uljTPWgp6kBTuxGc8MY+sUby77XYQDb7J7/sVcxc0u24ziEMbpNfouU+PDultg5C/S47nmnjVamhUFBqDvqHW5CUjLC2IVeWQd/orQEeY8nSlSNN1TnGb0AUgdKPRxMWhali42sIgnIaC49BsJgYJ/zUdJAwpxNy5E45f+phocPhuRCPTxOyp87MKTmz2CysagRUgiznVQR2FwKiEnG8s9x0X2vHm1zSrzmvzwXKM3sT/5Y7+fMPaDDVq+F8BkWWAGMxFJGRFh8dSdNOcl1LQMvZ3zEGT78GZLX+8mmjhNRps4prSCNPyUxfY2+5+t52cJ2uarx0sYIE6g4PbwP4l9D8pUqhaIpxnQ4jUcUNWzFmc6u6eJ9NZm877SbLszYwFZwa9+upnLXTd9sqtdNXN/fSGoZrUjefn9nnT+2Eyx3NzlHaIevfZRy90shoVoczEAD0f/bL+OjxPkz/njfXQngjrHkXoydgHi/hOQkReQYQ8O72XyJ7irKZq0XYKK/Dxi6+A4gpQaD21XzfbAC/WAsQHAnwHDOO1PI/kSui6LQY864MNrZT1eXiHYLFwu7MdTTG4=
  - secure: BQXOKLOKbxnVBTbDYG6riI75eROUOwO/XcikVd02HIU0o1ecfFjiJnIYs13GGLGF6FrVThfS1HVzs1OvGNCCJhGDixCpViG3DU6+oBNZvFHzKGnl3LcguDXCLacbK/ahjdL5kt3d+rP5xJprr4lKiNy/sqUB2dDJnGRACIT17vG+P/iETYbZiPBLvgbl8N7kjPcrkdau8BRlqaLbP52gJ5jvx7r27q7vQKKUQmNTNydRXJT4Vpb+bwbOt0upTNLUwKu8JxzDKYIvgo/JWoBrBOp3LiKpYKNKnj+KtbWyAztufnirSFkqGzCS+28X8PlQoKMZ0/nMtg7UIAVQwWWQNeRKxoo2r8q579vkFBv2du6XR8Ap5JYKSq82dt4wzk6PI3Gw3Hdwney8dzxuTJuZCcOsHzIpImPvn+wDgOKMkI++09jkiIeC681tPcu3IG9wteCuKc2sxQNSc7y2NDT4lxwVCtZSHzuk+rPOcQq/LtEh36Wan/CkG6XanIlmrlrkJ36dSA8aNYN8iiUyMbpzdAD4bo4LzOAQrYJSayJiktbK7i1WYh0dwtqbegi6GCt4iWFsf5GhLsmCROMqAKUmmtbveZPa37jfHrGgI1gSbb14R+jtQ9PZAxZsSNjL+csdPK+yy9WFo8VbcyrUm3q3GvEar6iYED5rmDml5tzEmHU=
  - secure: VBapjxDQpekHpUi1Ud91Mc9YmeqtKbYIYgQpkkQCapWFqUGyH5FXMboKZPAA3SbdMQe/at4T8JihJ7jmTiKw2WW38jtTsVayACev9qsvAP3tnNjAxw4XC7N9uqAGRaWJfa3hG1cEGrscXAQgC4zzrsj97Q0+/eI+RXssTsscd8xtEVDQYBRrav7OgnrziFlDE6+WQTBbjOYOhHmv64MIrCD3g3oIdYUfdO5ar1qhu/+NyCNk9vNG33EItK8YdFE355dU2hfqolmqEXBChKAUCGgxuDHj0p94jWeoRSapW6JqsPKPQYA6QS60/67KnbcLzrYvqXTY31eWnHaLRYmLfcelhPjK7wL09rXbUyBgbc1DqVwHWQBBuPmLXKeG3ldwZKzwEyXwwVSnjjXSgRJxEyq968+WX2qeCqxgQB3JGimDLfdf8nqxsYpMmsBp7LJiB9erYdyced5h6pyDisX51TEX2goaHCjTlevgEOOPAo3PIUCIbjvhN++gZYMLC5SzG0gXATq3w0I/Jtmk3DUh67Dp3g9LzdRN0KuK+EfRCKHPOGqGxopD1oqK49Jp8H/d2+2Dujw6aGmTGXCvzFUFD8AgElYaiem965OTxr4i4dqUJcF+YDqxwExAIPZwHM1C4JZy41OrFmhiqV/Wr3YbCnAKthFZWDdof0DavProUr8=
